apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: linkerd
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`linkerd.rusik.dev`)
    kind: Rule
    services:
    - name: linkerd-web
      port: 8084
    tls:
      certResolver: default