apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: web-ingress-auth
  namespace: linkerd
data:
  auth: YWRtaW46JGFwcjEkdVRTY2x4bUMkeElOMkdYSDI3OHZhakFmSXZKTm51LgoK
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: linkerd
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:linkerd-web.linkerd.svc.cluster.local:8084
    traefik.ingress.kubernetes.io/auth-type: basic
    traefik.ingress.kubernetes.io/auth-secret: grafana-ingress-auth
spec:
  rules:
  - host: dashboard.linkerd.rusik.dev
    http:
      paths:
      - backend:
          serviceName: linkerd-web
          servicePort: 8084
