{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catsanddogs.serviceAccountName" . }}
  labels:
{{ include "catsanddogs.labels" . | nindent 4 }}
{{- end -}}
